### ISSUE TITLE
Poly class method String fails to parse some valid expressions

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#194]
Quick example. This works as expected

```python
>> import galois
>> from galois import GF2
>> galois.Poly.String("x^2-1", field=GF2)
Poly(x^2 + 1, GF(2))
```
But if ordering is ascending, it doesn't

```python
>> import galois
>> from galois import GF2
>> galois.Poly.String("1 - x^2", field=GF2)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "galois/galois/_polys/_poly.py", line 388, in String
    return Poly.Degrees(*str_to_sparse_poly(string), field=field)
  File "galois/galois/_poly_conversion.py", line 230, in str_to_sparse_poly
    coeff = int(coeff) if coeff != "" else 1
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by iyanmv** [comment]
The problem is this line
https://github.com/mhostetter/galois/blob/4b9c52175a8b6ec999bc429475dc20a1cfcae2cb/galois/_poly_conversion.py#L217

**Comment by mhostetter** [comment]
Thanks for pointing this out. This is a valid bug, and I can reproduce it.
