### ISSUE TITLE
OverflowError: int too big to convert on x.minimal_poly()

### ISSUE THREAD

**Issue by geostergiop** [mhostetter/galois#355]
Hi Matt,

It's been a while. I got a new error that might be a bug, check this out.

```
line = "256, 246, 144, 9, 0"
degrees = list(map(int, line.split(",")))

poly = galois.Poly.Degrees(degrees)    
GF = galois.GF((2**256),irreducible_poly=poly, primitive_element=2, verify=False)
print(GF.properties)

x = GF(12619776604307790469550660645393525758448419897555601226868753617320214526993)
print(x.minimal_poly())
```
throws the following error (does not happen with other cases) even though the GF field is constructed correctly and `x` < order. 
```
GF(2^256):
  characteristic: 2
  degree: 256
  order: 115792089237316195423570985008687907853269984665640564039457584007913129639936
  irreducible_poly: x^256 + x^246 + x^144 + x^9 + 1
  is_primitive_poly: True
  primitive_element: x
Traceback (most recent call last):
  File "linear.py", line 495, in <module>
    zp, op = execute(pt)
  File "linear.py", line 433, in execute
    result, failedAt, bintest = looptest(privkey, pt, GF)
  File "linear.py", line 316, in looptest
    print(x.minimal_poly())
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_main.py", line 1965, in minimal_poly
    return self._minimal_poly_element()
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_main.py", line 1981, in _minimal_poly_element
    poly = Poly(poly.coeffs, field=field.prime_subfield)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_main.py", line 2679, in __new__
    coeffs, field = cls._convert_coeffs(coeffs, field)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_main.py", line 2704, in _convert_coeffs
    coeffs = np.array(coeffs, dtype=field.dtypes[-1])
OverflowError: int too big to convert
```
Thank you for your time, as always.
G

**Comment by geostergiop** [comment]
Update:
After updating to the latest version of galois (was previously at 0.23), the error changed to the following (same code used):
```
Traceback (most recent call last):
  File "linear.py", line 495, in <module>
    zp, op = execute(pt)
  File "linear.py", line 433, in execute
    result, failedAt, bintest = looptest(privkey, pt, GF)
  File "linear.py", line 316, in looptest
    print(x.minimal_poly())
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_array.py", line 2061, in minimal_poly
    return self._minimal_poly_element()
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_array.py", line 2077, in _minimal_poly_element
    poly = Poly(poly.coeffs, field=field.prime_subfield)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_polys\_poly.py", line 100, in __init__
    self._coeffs, self._field = self._convert_coeffs(coeffs, field)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_polys\_poly.py", line 127, in _convert_coeffs
    coeffs = field(coeffs)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_array.py", line 569, in __new__
    return super().__new__(cls, x, dtype, copy, order, ndmin)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_domains\_array.py", line 193, in __new__
    x = cls._verify_array_like_types_and_values(x)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_array.py", line 626, in _verify_array_like_types_and_values
    cls._verify_array_values(x)
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python38\lib\site-packages\galois\_fields\_array.py", line 651, in _verify_array_values
    raise ValueError(f"{cls.name} arrays must have elements in `0 <= x < {cls.order}`, not {values}.")
```

**Comment by mhostetter** [comment]
Hey George. You'll definitely want to use newer versions because there were a lot of speed ups in binary polynomial arithmetic, see [here](https://galois.readthedocs.io/en/latest/release-notes/v0.0.26.html).

Thanks for reporting this and providing the reproducible example and output.

While the code may raise the exception in a different place, the underlying error is still the same between versions. The issue is that the "irreducible" polynomial for `GF(2^256)` is actually not irreducible. So the minimal polynomial computation doesn't map a `GF(2^256)` element to a polynomial over `GF(2)`. The issue is that the "Galois field" actually isn't a field.


```python
In [1]: import galois

In [2]: f = galois.Poly.Degrees([256, 246, 144, 9, 0]); f
Out[2]: Poly(x^256 + x^246 + x^144 + x^9 + 1, GF(2))

In [3]: galois.is_irreducible(f)
Out[3]: False

In [4]: factors, exponents = galois.factors(f); factors, exponents
Out[4]: 
([Poly(x^10 + x^6 + x^5 + x^3 + x^2 + x + 1, GF(2)),
  Poly(x^13 + x^12 + x^11 + x^7 + x^6 + x^3 + x^2 + x + 1, GF(2)),
  Poly(x^18 + x^17 + x^15 + x^10 + x^9 + x^7 + x^5 + x^2 + 1, GF(2)),
  Poly(x^23 + x^19 + x^17 + x^16 + x^13 + x^8 + x^6 + x^5 + x^4 + x + 1, GF(2)),
  Poly(x^49 + x^46 + x^43 + x^42 + x^40 + x^38 + x^37 + x^36 + x^32 + x^31 + x^28 + x^27 + x^26 + x^23 + x^21 + x^18 + x^13 + x^11 + x^8 + x^6 + x^5 + x^4 + x^3 
+ x + 1, GF(2)),
  Poly(x^63 + x^62 + x^60 + x^58 + x^57 + x^55 + x^53 + x^51 + x^50 + x^48 + x^45 + x^42 + x^40 + x^39 + x^38 + x^35 + x^34 + x^33 + x^32 + x^30 + x^29 + x^28 + 
x^27 + x^26 + x^20 + x^19 + x^18 + x^15 + x^14 + x^12 + x^11 + x^7 + x^3 + x^2 + 1, GF(2)),
  Poly(x^80 + x^79 + x^78 + x^77 + x^76 + x^75 + x^73 + x^71 + x^69 + x^68 + x^67 + x^66 + x^65 + x^64 + x^62 + x^61 + x^58 + x^57 + x^54 + x^46 + x^45 + x^43 + 
x^42 + x^40 + x^38 + x^36 + x^34 + x^27 + x^26 + x^25 + x^24 + x^21 + x^18 + x^17 + x^16 + x^15 + x^12 + x^11 + x^10 + x^6 + 1, GF(2))],
 [1, 1, 1, 1, 1, 1, 1])

In [5]: galois.prod(*factors)
Out[5]: Poly(x^256 + x^246 + x^144 + x^9 + 1, GF(2))

In [6]: f
Out[6]: Poly(x^256 + x^246 + x^144 + x^9 + 1, GF(2))
```

**Comment by geostergiop** [comment]
Thanks Matt, was able to identify this through the second error indeed.

**Comment by mhostetter** [comment]
Cool. I guess a good side effect of some of the recent refactoring is that scenario produces better error outputs.
