### ISSUE TITLE
numpy.sum() returns inconsistent types

### ISSUE THREAD

**Issue by tshead2** [mhostetter/galois#444]
With 0D FieldArray inputs, numpy.sum() returns a FieldArray, as expected:

```python
import galois
import numpy

>>> f = galois.Field(2**64-59)
>>> a = f.Random()
>>> b = f.Random()
>>> numpy.sum([a, b], axis=0)
GF(5802771140473745109, order=18446744073709551557)
```

However, with 1D FieldArray inputs, numpy.sum() returns a numpy.ndarray:

```python
>>> a = f.Random((2,))
>>> b = f.Random((2,))
>>> numpy.sum([a, b], axis=0)
array([27182153923255896342, 13808647080647953998], dtype=object)
```

I've verified that numpy.add.reduce() works the same, and sum() doesn't have a `subok` argument.  Is this expected behavior?

Cheers,
Tim

**Comment by mhostetter** [comment]
Hey Tim, thanks for the bug report. I can reproduce.

I believe the issue is related to the input to `np.sum()` being a list of arrays as opposed to a single array, see my below example. However, I can agree `galois` should handle this and return the correct type. I'll look into it.

```python
In [1]: import numpy as np

In [2]: import galois

In [3]: GF = galois.Field(2**64 - 59)

In [4]: a = GF([1, 2]); a
Out[4]: GF([1, 2], order=18446744073709551557)

In [5]: b = GF([3, 4]); b
Out[5]: GF([3, 4], order=18446744073709551557)

In [6]: np.sum([a, b], axis=0)
Out[6]: array([4, 6], dtype=object)

In [7]: np.sum([a, b], axis=1)
Out[7]: array([3, 7], dtype=object)

In [8]: c = np.vstack([a, b]); c
Out[8]: 
GF([[1, 2],
    [3, 4]], order=18446744073709551557)

In [9]: np.sum(c, axis=0)
Out[9]: GF([4, 6], order=18446744073709551557)

In [10]: np.sum(c, axis=1)
Out[10]: GF([3, 7], order=18446744073709551557)
```

**Comment by mhostetter** [comment]
Upon further investigation with the debugger, I do not believe this is a bug and *is* expected behavior. Here's why:

NumPy in `np.sum()` uses the type of the input to determine which function/ufunc to dispatch. In your case, the input is a list. So NumPy converts the list to a `np.ndarray` and then calls the standard `np.sum()` implementation. However, we want the Galois field `np.add.reduce()` ufunc to be dispatched by `np.sum()`. In order for NumPy to know this, the input type must be the appropriate `FieldArray` subclass. So in your case, I believe you need to do `np.vstack([a, b])` first.

We can confirm this by viewing a smaller example and seeing that `np.sum([a, b], axis=0)` invokes integer addition and yields the incorrect result.

```python
In [1]: import numpy as np

In [2]: import galois

In [3]: GF = galois.GF(5)

In [4]: a = GF([1, 2]); a
Out[4]: GF([1, 2], order=5)

In [5]: b = GF([3, 4]); b
Out[5]: GF([3, 4], order=5)

# Normal addition is invoked
In [6]: np.sum([a, b], axis=0)
Out[6]: array([4, 6], dtype=uint64)

# Normal addition is invoked
In [7]: np.sum([a, b], axis=1)
Out[7]: array([3, 7], dtype=uint64)

In [8]: c = np.vstack([a, b]); c
Out[8]: 
GF([[1, 2],
    [3, 4]], order=5)

In [9]: np.sum(c, axis=0)
Out[9]: GF([4, 1], order=5)

In [10]: np.sum(c, axis=1)
Out[10]: GF([3, 2], order=5)
```

**Comment by tshead2** [comment]
Matt:

That makes sense and I appreciate the quick response, unfortunately I run into a much more serious problem trying to reproduce your example:

```python
>>> # ... copied verbatim from above ...
>>> c = np.vstack([a, b]); c
GF([[1, 2],
    [3, 4]], order=5)
>>> np.sum(c, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in sum
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/galois/_domains/_function.py", line 343, in __array_function__
    output = super().__array_function__(func, types, args, kwargs)  # pylint: disable=no-member
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2259, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py", line 48, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/galois/_domains/_ufunc.py", line 578, in __array_ufunc__
    return getattr(field, field._OVERRIDDEN_UFUNCS[ufunc])(ufunc, method, inputs, kwargs, meta)
  File "/Users/tshead/miniconda3/lib/python3.8/site-packages/galois/_domains/_ufunc.py", line 281, in __call__
    output = getattr(self.ufunc, method)(*inputs, **kwargs)
TypeError: reduce() takes from 1 to 7 positional arguments but 140404360324160 were given
```

The usual details:

```python
>>> sys.version
'3.8.13 (default, Mar 28 2022, 06:16:26) \n[Clang 12.0.0 ]'
>>> np.__version__
'1.21.2'
>>> galois.__version__
'0.2.0'
```

**Comment by mhostetter** [comment]
Oh my... 

After trying several configs, I was able to reproduce with Python 3.7.9, NumPy 1.21.2, and `galois` 0.2.0 in Windows. I'll start looking into the bug. I've seen weird things on Windows before....

<details>
<summary>Example</summary>

```python
PS C:\Users\matth\repos\galois> python3 -m IPython
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np; np.__version__
Out[1]: '1.21.2'

In [2]: import galois; galois.__version__
Out[2]: '0.2.0'

In [3]: GF = galois.GF(5)

In [4]: a = GF([1, 2]); a
Out[4]: GF([1, 2], order=5)

In [5]: b = GF([3, 4]); b
Out[5]: GF([3, 4], order=5)

In [6]: c = np.vstack([a, b]); c
Out[6]: 
GF([[1, 2],
    [3, 4]], order=5)

In [7]: np.sum(a, axis=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-6b36336d34b8> in <module>
----> 1 np.sum(a, axis=0)

<__array_function__ internals> in sum(*args, **kwargs)

~\repos\galois\src\galois\_domains\_function.py in __array_function__(self, func, types, args, kwargs)
    341                 args = tuple(args)
    342
--> 343             output = super().__array_function__(func, types, args, kwargs)  # pylint: disable=no-member
    344
    345             if func in field._FUNCTIONS_REQUIRING_VIEW:

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\fromnumeric.py in sum(a, axis, dtype, out, keepdims, initial, where)
   2258
   2259     return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
-> 2260                           initial=initial, where=where)
   2261 
   2262

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     82                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     83             else:
---> 84                 return reduction(axis=axis, out=out, **passkwargs)
     85
     86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\_methods.py in _sum(a, axis, dtype, out, keepdims, initial, where)
     46 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
     47          initial=_NoValue, where=True):
---> 48     return umr_sum(a, axis, dtype, out, keepdims, initial, where)
     49
     50 def _prod(a, axis=None, dtype=None, out=None, keepdims=False,

~\repos\galois\src\galois\_domains\_ufunc.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    576                 kwargs["dtype"] = field.dtypes[-1]
    577
--> 578             return getattr(field, field._OVERRIDDEN_UFUNCS[ufunc])(ufunc, method, inputs, kwargs, meta)
    579
    580         elif ufunc in field._UNSUPPORTED_UFUNCS:

~\repos\galois\src\galois\_domains\_ufunc.py in __call__(self, ufunc, method, inputs, kwargs, meta)
    279         self._verify_operands_in_same_field(ufunc, inputs, meta)
    280         inputs, kwargs = self._view_inputs_as_ndarray(inputs, kwargs)
--> 281         output = getattr(self.ufunc, method)(*inputs, **kwargs)
    282         output = self._view_output_as_field(output, self.field, meta["dtype"])
    283         return output

TypeError: reduce() takes from 1 to 7 positional arguments but 2461666315064 were given
```
</details>

**Comment by tshead2** [comment]
I should have mentioned that this was on a Mac, with Python provided by Conda.

Cheers,
Tim

**Comment by mhostetter** [comment]
> I should have mentioned that this was on a Mac

Oh... double yikes. If it's appearing on two platforms that means it's more serious.

What version of Numba do you have installed?

**Comment by tshead2** [comment]
```python
>>> numba.__version__
'0.53.1'
```

Cheers,
Tim

**Comment by tshead2** [comment]
Yes, that works now ... Python 3.10.8, Numpy 1.23.5, Numba 0.56.4, and Galois version 0.3.0 (I see you snuck that in there).

Many thanks,
Tim

**Comment by mhostetter** [comment]
No problem. Is this issue good to close?
