### ISSUE TITLE
plu_decompose returns IndexError

### ISSUE THREAD

**Issue by davikrehalt** [mhostetter/galois#476]
Hi, hopefully I'm not missing anything obvious but it seems that the following matrix

GF([[1, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0, 1],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1]], order=2)

returns an IndexError when I ask for its PLU decomposition. Is this normal?

 b.plu_decompose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davikrehalt/Library/Python/3.9/lib/python/site-packages/galois/_fields/_array.py", line 1243, in plu_decompose
    P, L, U, _ = _linalg.plu_decompose_jit(field)(A)
  File "/Users/davikrehalt/Library/Python/3.9/lib/python/site-packages/galois/_domains/_linalg.py", line 353, in __call__
    if Ai[i, i] == 0:
  File "/Users/davikrehalt/Library/Python/3.9/lib/python/site-packages/galois/_domains/_array.py", line 415, in __getitem__
    item = super().__getitem__(key)
IndexError: index 6 is out of bounds for axis 1 with size 6

**Comment by mhostetter** [comment]
Thanks for the report! This is a bug and I can reproduce. I will look into this tomorrow.

```python
In [1]: import galois

In [2]: GF = galois.GF(2)

In [3]: A = GF([[1, 0, 0, 0, 0, 1],
   ...: [1, 1, 1, 1, 0, 1],
   ...: [1, 0, 0, 0, 0, 0],
   ...: [0, 1, 0, 0, 0, 0],
   ...: [0, 0, 1, 0, 0, 0],
   ...: [0, 0, 0, 1, 0, 0],
   ...: [0, 0, 0, 0, 1, 0],
   ...: [0, 0, 0, 0, 0, 1]]); A
Out[3]: 
GF([[1, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0, 1],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1]], order=2)

In [4]: A.plu_decompose()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 A.plu_decompose()

File /mnt/c/Users/matth/repos/galois/src/galois/_fields/_array.py:1243, in FieldArray.plu_decompose(self)
   1241 field = type(self)
   1242 A = self
-> 1243 P, L, U, _ = _linalg.plu_decompose_jit(field)(A)
   1244 return P, L, U

File /mnt/c/Users/matth/repos/galois/src/galois/_domains/_linalg.py:353, in plu_decompose_jit.__call__(self, A)
    350 N_permutations = 0  # Number of permutations
    352 for i in range(0, n - 1):
--> 353     if Ai[i, i] == 0:
    354         idxs = np.nonzero(Ai[i:, i])[0]  # The first non-zero entry in column `i` below row `i`
    355         if idxs.size == 0:

File /mnt/c/Users/matth/repos/galois/src/galois/_domains/_array.py:415, in Array.__getitem__(self, key)
    410 def __getitem__(self, key):
    411     """
    412     Ensure that slices that return a single value return a 0-D Galois field array and not a single integer. This
    413     ensures subsequent arithmetic with the finite field scalar works properly.
    414     """
--> 415     item = super().__getitem__(key)
    416     if np.isscalar(item):
    417         item = self.__class__(item, dtype=self.dtype)

IndexError: index 6 is out of bounds for axis 1 with size 6
```

**Comment by davikrehalt** [comment]
Hi! any updates on this? If you point me to the code I can try to help.

**Comment by mhostetter** [comment]
Apologies, I've been distracted. The offending code is in this function.

https://github.com/mhostetter/galois/blob/db0fde5c6a6fc140c753528eb6b62c67313e0b86/src/galois/_domains/_linalg.py#L341-L375

`n` likely needs to be the lesser of `A.shape[0]` and `A.shape[1]`. I may be able to look into it tonight. Help is always appreciated.

**Comment by davikrehalt** [comment]
Hi! It seems that it works for me!

**Comment by mhostetter** [comment]
Bug fix released in v0.3.4.
